export const GET_MEALS = "GET_MEALS";
export const GET_SINGLE_MEAL = "GET_SINGLE_MEAL";
export const RESET_MEAL_SEARCH = "RESET_MEAL_SEARCH";
export const FAVORITE_A_MEAL = "FAVORITE_A_MEAL";
export const GET_FAVORITES = "GET_FAVORITES";
export const SCHEDULE_MEAL = "SCHEDULE_MEAL";
export const CANCEL_SCHEDULED_MEAL = "CANCEL_SCHEDULED_MEAL";
export const GET_SCHEDULED_MEALS = "GET_SCHEDULED_MEALS";
